print ("====== BIODATA MAHASISWA ======")
print ("Nama:", "Muhammad Nazril Fandhi")
print ("NIM:", "2611532034")
print ("Program Studi:", "Informatika")
print ("Kelas:", "B")
print ("Fakultas:", "Teknologi Informasi")
print ("====== UNIVERSITAS ANDALAS ======")
print (" ")
print (" ")
print("             /\\")
print("            /  \\")
print("           /    \\")
print("          /______\\")
print("         /|      |\\")
print("        / |      | \\")
print("       /__|______|__\\")
print("       |            |")
print("       |   ____     |")
print("       |  |    |    |")
print("       |  | [] |    |")
print("       |  |____|    |")
print("       |            |")
print("       | []      [] |")
print("       |____________|")